### ISSUE TITLE
maintenance costs 建议翻译为 “维护费用”

### ISSUE THREAD

**Issue by icemoon1987** [cloudwu/xenonauts#14]
hi，maintenance costs 建议统一翻译为 “维护费用”，请问是我直接在 wiki 的那个“待补充” 修改吗？还是您这边统一维护？

**Comment by cloudwu** [comment]
wiki  可以任何人编辑。你直接加就好

**Comment by laixintao** [comment]
你新建一个 wiki 吧，建议做个“费用”之类的页面，统一建造费用 维护费用等等

**Comment by cloudwu** [comment]
任何人都可以新建页面的。那个 type 也不是我建的呀 :)
