### ISSUE TITLE
extraterrestrial 译法

### ISSUE THREAD

**Issue by zsbwalker** [cloudwu/xenonauts#20]
extraterrestrial 一词仅适合在部分段落译作“天外来客”，比如标题什么的，在游戏内这么翻译是否符合游戏风格？（感觉稍显文艺）   感觉之前的地外文明、外星生物之类的叫法更现实风格一些。

**Comment by cloudwu** [comment]
对的。 只是用在标题上的。因为这是一个大分类。在这个分类下多半是和外星人有关的事件，信息等等。 因为要和 Alien XXX 翻译成 外星 XX 显出不同。

我觉得在内文中翻译成 外星人就可以了。外星生物也可以。

**Comment by zsbwalker** [comment]
好的
