### ISSUE TITLE
Xenonauts在某些情况下可否以为航员呢？

### ISSUE THREAD

**Issue by laixintao** [cloudwu/xenonauts#5]
例如这一句：
The Medical Center structure provides Xenonauts with state-of-the-art medical care

我想译作
医疗中心为航员提供最先进的医疗服务

如果必须统一的话，我就把这个地方改过来：
医疗中心为Xenonauts提供最先进的医疗服务

**Comment by cloudwu** [comment]
我觉得可以统一先不翻， 然后大家讨论一下再全部做全文替换也容易。当然局部的翻译以中文读起来舒服，表达好意思即可。

比如这里翻译成队员等等都可以，没必要每个字都直接翻译。
