### ISSUE TITLE
Researches.AlienAlloyProduction.txt 内容可疑

### ISSUE THREAD

**Issue by shunner** [cloudwu/xenonauts#67]
Researches.AleniumEnrichment.txt 以及
Researches.AlienAlloyProduction.txt 疑似生成有误，请检查并澄清~

**Comment by cloudwu** [comment]
原文在仓库里有,  https://github.com/cloudwu/xenonauts/blob/master/xenopedia.eng.xml

**Comment by shunner** [comment]
发现是原文的问题！上述文件，从1242到1306行。

**Comment by cloudwu** [comment]
See also : https://github.com/cloudwu/xenonauts/issues/21
